{% set goname = "syft" %}
{% set version = "0.99.0" %}


package:
  name: {{ goname|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: src
    url: https://github.com/anchore/syft/archive/v{{ version }}.tar.gz
    sha256: 4abf63a8377c3422bb94d44ccaff0cac66c64ee74b0c4c77769360fb72a2cf71
  - url: https://gitlab.com/cznic/mathutil/-/raw/b13e5b5643328f15fd2fcedc85f647f0d8f9180f/LICENSE  # v1.5.0
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    fn: LICENSE-mathutil
  - url: https://raw.githubusercontent.com/xi2/xz/48954b6210f8d154cb5f8484d3a3e1f83489309e/LICENSE
    sha256: 5c640056d513f276d56635af7a0bed81cb7eac02a31b6e56d40c416557a8d8ce
    fn: LICENSE-xz

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - syft --version | grep {{ version }}

about:
  home: https://github.com/anchore/syft
  license: Apache-2.0
  license_family: Apache
  license_file:
    - src/LICENSE
    - library_licenses/
    - LICENSE-xz
    - LICENSE-mathutil
  summary: CLI tool and library for generating a Software Bill of Materials from container images and filesystems

extra:
  recipe-maintainers:
    - janjagusch
