schema_version: 1

context:
  goname: syft
  version: "1.33.0"

package:
  name: ${{ goname|lower }}
  version: ${{ version|replace("-", "_") }}

source:
  - url: https://github.com/anchore/syft/archive/v${{ version }}.tar.gz
    sha256: 7cc0454183d72d7771fd25e7c8fd0469c4881827c3a36a3e3cbb912777b680d9
    target_directory: src
  - url: https://gitlab.com/cznic/mathutil/-/raw/b13e5b5643328f15fd2fcedc85f647f0d8f9180f/LICENSE  # v1.5.0
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    file_name: LICENSE-mathutil
  - url: https://raw.githubusercontent.com/xi2/xz/48954b6210f8d154cb5f8484d3a3e1f83489309e/LICENSE
    sha256: 5c640056d513f276d56635af7a0bed81cb7eac02a31b6e56d40c416557a8d8ce
    file_name: LICENSE-xz

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - syft --version | grep ${{ version }}

about:
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
    - LICENSE-xz
    - LICENSE-mathutil
  summary: CLI tool and library for generating a Software Bill of Materials from container images and filesystems
  homepage: https://github.com/anchore/syft

extra:
  recipe-maintainers:
    - janjagusch
